export const REGISTER_ACCOUNT_REQUEST = 'REGISTER_ACCOUNT_REQUEST';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAIL = 'REGISTER_ACCOUNT_FAIL';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const LOGIN_WITH_SOCIAL_REQUEST = 'LOGIN_WITH_SOCIAL_REQUEST';
export const LOGIN_WITH_SOCIAL_SUCCESS = 'LOGIN_WITH_SOCIAL_SUCCESS';
export const LOGIN_WITH_SOCIAL_FAIL = 'LOGIN_WITH_SOCIAL_FAIL';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL = 'SIGN_OUT_FAIL';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVARTA_REQUEST';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVARTA_SUCCESS';
export const UPDATE_AVATAR_FAIL = 'UPDATE_AVARTA_FAIL';

export const SIGN_OUT = 'SIGN_OUT';

export const SET_TOKEN_TO_REQUEST_HEADER = 'SET_TOKEN_TO_REQUEST_HEADER';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const SAVE_POST_REQUEST = 'SAVE_POST_REQUEST';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_FAIL = 'SAVE_POST_FAIL';

export const GET_MY_POST_REQUEST = 'GET_MY_POST_REQUEST';
export const GET_MY_POST_SUCCESS = 'GET_MY_POST_SUCCESS';
export const GET_MY_POST_FAIL = 'GET_MY_POST_FAIL';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const TOOGLE_LIKE_POST_REQUEST = 'TOOGLE_LIKE_POST_REQUEST';
export const TOOGLE_LIKE_POST_SUCCESS = 'TOOGLE_LIKE_POST_SUCCESS';
export const TOOGLE_LIKE_POST_FAIL = 'TOOGLE_LIKE_POST_FAIL';

export const RESEND_VERIFY_ACCOUNT_EMAIL_REQUEST = 'RESEND_VERIFY_ACCOUNT_EMAIL_REQUEST';
export const RESEND_VERIFY_ACCOUNT_EMAIL_SUCCESS = 'RESEND_VERIFY_ACCOUNT_EMAIL_SUCCESS';
export const RESEND_VERIFY_ACCOUNT_EMAIL_FAIL = 'RESEND_VERIFY_ACCOUNT_EMAIL_FAIL';

export const OPEN_POST_LINKING = 'OPEN_POST_LINKING';
